// flow-typed signature: f55c95e506137abdd6c706d4fcb3755d
// flow-typed version: <<STUB>>/gatsby-plugin-styled-jsx_v~3.0.3/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-plugin-styled-jsx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-plugin-styled-jsx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-plugin-styled-jsx/gatsby-node' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-styled-jsx/gatsby-ssr' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-plugin-styled-jsx/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby-plugin-styled-jsx/gatsby-node'>;
}
declare module 'gatsby-plugin-styled-jsx/gatsby-ssr.js' {
  declare module.exports: $Exports<'gatsby-plugin-styled-jsx/gatsby-ssr'>;
}
declare module 'gatsby-plugin-styled-jsx/index' {
  declare module.exports: $Exports<'gatsby-plugin-styled-jsx'>;
}
declare module 'gatsby-plugin-styled-jsx/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-styled-jsx'>;
}
