// flow-typed signature: bc7e5ee3c1d81d81b98f31d2cd8ac962
// flow-typed version: <<STUB>>/gatsby-plugin-sharp_v^1.6.21/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-plugin-sharp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-plugin-sharp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-plugin-sharp/duotone' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-sharp/gatsby-node' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-plugin-sharp/duotone.js' {
  declare module.exports: $Exports<'gatsby-plugin-sharp/duotone'>;
}
declare module 'gatsby-plugin-sharp/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby-plugin-sharp/gatsby-node'>;
}
declare module 'gatsby-plugin-sharp/index' {
  declare module.exports: $Exports<'gatsby-plugin-sharp'>;
}
declare module 'gatsby-plugin-sharp/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-sharp'>;
}
