// flow-typed signature: 8c5035c43d89d3c2e45ee023ad95c7d7
// flow-typed version: <<STUB>>/safe-access_v^0.1.0/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'safe-access'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'safe-access' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'safe-access/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'safe-access/index' {
  declare module.exports: $Exports<'safe-access'>;
}
declare module 'safe-access/index.js' {
  declare module.exports: $Exports<'safe-access'>;
}
declare module 'safe-access/test.js' {
  declare module.exports: $Exports<'safe-access/test'>;
}
