// flow-typed signature: 01cd555c80bdd5a48ee1feeacd4eaa41
// flow-typed version: <<STUB>>/sanitize.css_v^8.0.0/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sanitize.css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sanitize.css' {
  declare module.exports: any;
}
