// flow-typed signature: ea2677fc60383ef6e8695f2c09050d3c
// flow-typed version: <<STUB>>/@mapbox/stylelint-processor-arbitrary-tags_v^0.2.0/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@mapbox/stylelint-processor-arbitrary-tags'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@mapbox/stylelint-processor-arbitrary-tags' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@mapbox/stylelint-processor-arbitrary-tags/lib/reindent' {
  declare module.exports: any;
}

// Filename aliases
declare module '@mapbox/stylelint-processor-arbitrary-tags/index' {
  declare module.exports: $Exports<'@mapbox/stylelint-processor-arbitrary-tags'>;
}
declare module '@mapbox/stylelint-processor-arbitrary-tags/index.js' {
  declare module.exports: $Exports<'@mapbox/stylelint-processor-arbitrary-tags'>;
}
declare module '@mapbox/stylelint-processor-arbitrary-tags/lib/reindent.js' {
  declare module.exports: $Exports<'@mapbox/stylelint-processor-arbitrary-tags/lib/reindent'>;
}
